### ISSUE TITLE
Still box dataset

### ISSUE THREAD

**Issue by Heng14** [ClementPinard/DepthNet#2]
great job! I tried to download still box dataset through torrent but it is really slow. Do you a faster solution for me to download it? Or just a part of it (like only the 512 set). Thank you so much!

**Comment by ClementPinard** [comment]
Hi, unfortunately, can only use torrent for the moment, as no server is avalaible for me to share it via a direct link :(

I am looking for alternatives, apparently, mega.co.nz seems to allow sharing 50GB files, so I'm going to upload it there and I'll send you a link if it works !

**Comment by ClementPinard** [comment]
https://mega.nz/#!TN8h0RrY!eQw2_9SjgwxYCUTa88-Dwaijk4Y_ZTsi7wKyrWkjKww

Let me know if it works better for you

Clément

**Comment by Heng14** [comment]
OK. Thank you so much. Actually, I have finished it through torrent and I am glad to have another way to download it. Many thanks to you~
