### ISSUE TITLE
Can't download the still box torrent?

### ISSUE THREAD

**Issue by 3togo** [ClementPinard/DepthNet#3]
any other means?

Joe

magnet:?xt=urn:btih:4d3a60ad3c9ceac7662735ba8e90fb467b43a3aa&tr=http%3A%2F%2Facademictorrents.com%2Fannounce.php&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce

**Comment by ClementPinard** [comment]
Hey ! unfortunately, this dataset is not easy to keep online, due to his size :(

I uploaded the 512px version in mega, you can get it here : https://mega.nz/#!TN8h0RrY!eQw2_9SjgwxYCUTa88-Dwaijk4Y_ZTsi7wKyrWkjKww

If you want the other parts, Maybe I can upload them on another account, as the 512 already takes up the whole 30GB storage :disappointed: 

let me know, I'll try my best to let you get.
And if by any mean you happen to have a solution for my dataset just let me know :smile:

**Comment by 3togo** [comment]
many thanks for your prompt reply. In the old days, we use emulehttps://www.emule-project.net/home/perl/general.cgi?l=1&rm=downloadbut it is no longer popular. Anyway, thanks again for your help. Have a nice day Joe28.08.2018, 03:03, "Clément Pinard" <notifications@github.com>:Hey ! unfortunately, this dataset is not easy to keep online, due to his size :(
I uploaded the 512px version in mega, you can get it here : https://mega.nz/#!TN8h0RrY!eQw2_9SjgwxYCUTa88-Dwaijk4Y_ZTsi7wKyrWkjKww
If you want the other parts, Maybe I can upload them on another account, as the 512 already takes up the whole 20GB storage <g-emoji class="g-emoji" alias="disappointed" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f61e.png">😞
let me know, I'll try my best to let you get.
And if by any mean you happen to have a solution for my dataset just let me know <g-emoji class="g-emoji" alias="smile" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f604.png">😄

**Comment by ClementPinard** [comment]
also I restarted my seedbox at home, maybe you can retry the torrent, at least for lower resolutions

**Comment by 3togo** [comment]
many thanksJoe上午3:23, 2018年8月28日, "Clément Pinard" <notifications@github.com>:also I restarted my seedbox at home, maybe you can retry the torrent, at least for lower resolutions

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

-- Sent from Yandex.Mail for mobile

**Comment by filliat** [comment]
Hello, 

je n'y avais pas pensé, mais je peux le mettre sur ma freebox, comme cela il restera toujours en ligne. Je viens de le mettre. 

david. 



David FILLIAT 

Directeur de l'U2IS 

Unité d'Informatique et Ingénierie des Systèmes 



Tel : +33 1 81 87 20 34 
[ https://www.ensta-paristech.fr/?utm-source=mails ] 	


ENSTA ParisTech 

828, boulevard des Maréchaux 

91120 PALAISEAU [ [ https://www.ensta-paristech.fr/fr/venir-ensta-paristech | plan ] ] 

[ https://www.ensta-paristech.fr/ | www.ensta-paristech.fr ] 


Nos réseaux : [ https://www.facebook.com/ENSTA.ParisTech | Facebook ] | [ https://www.twitter.com/ENSTAParisTech | Twitter ] | [ https://plus.google.com/+ENSTA-ParisTechFr/posts | Google+ ] | [ https://www.youtube.com/user/ENSTAParisTech | YouTube ] | [ https://www.linkedin.com/company/ensta | LinkedIn ]

**Comment by 3togo** [comment]
David,Many thanksJoe上午4:09, 2018年8月28日, filliat <notifications@github.com>:Hello, 

je n'y avais pas pensé, mais je peux le mettre sur ma freebox, comme cela il restera toujours en ligne. Je viens de le mettre. 

david. 



David FILLIAT 

Directeur de l'U2IS 

Unité d'Informatique et Ingénierie des Systèmes 



Tel : +33 1 81 87 20 34 
[ https://www.ensta-paristech.fr/?utm-source=mails ] 	


ENSTA ParisTech 

828, boulevard des Maréchaux 

91120 PALAISEAU [ [ https://www.ensta-paristech.fr/fr/venir-ensta-paristech | plan ] ] 

[ https://www.ensta-paristech.fr/ | www.ensta-paristech.fr ] 


Nos réseaux : [ https://www.facebook.com/ENSTA.ParisTech | Facebook ] | [ https://www.twitter.com/ENSTAParisTech | Twitter ] | [ https://plus.google.com/+ENSTA-ParisTechFr/posts | Google+ ] | [ https://www.youtube.com/user/ENSTAParisTech | YouTube ] | [ https://www.linkedin.com/company/ensta | LinkedIn ]
