### ISSUE TITLE
How to use more than one graphic cards?

### ISSUE THREAD

**Issue by 3togo** [ClementPinard/DepthNet#4]
Based on the nvidia-smi, only one graphic card is used when I run 
>python3 train.py -j8 --lr 0.01 /path/to/still_box/64/ --log-output --activation-function elu --bn

My question is how can I use another graphic card, say I got two 1080Tl

Joe

jc@marvel-001:~$ nvidia-smi
Sun Sep  2 16:26:40 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.44                 Driver Version: 396.44                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:04:00.0 Off |                  N/A |
| 29%   40C    P8     7W / 180W |   2892MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 00000000:08:00.0 Off |                  N/A |
| 27%   30C    P8     6W / 180W |     10MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 1080    Off  | 00000000:09:00.0 Off |                  N/A |
| 27%   27C    P8     6W / 180W |     10MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 1080    Off  | 00000000:83:00.0 Off |                  N/A |
| 27%   29C    P8     6W / 180W |     10MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 1080    Off  | 00000000:84:00.0 Off |                  N/A |
| 27%   31C    P8     6W / 180W |     10MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 1080    Off  | 00000000:88:00.0 Off |                  N/A |
| 27%   29C    P8     6W / 180W |     10MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      9275      C   python3                                      497MiB |
|    0     11041      C   python3                                     2383MiB |
+-----------------------------------------------------------------------------+

**Comment by ClementPinard** [comment]
I implemented the method from `nn.DataParallel` to make it compatible with multiple gpus, but I don't have a multiple GPU steup, so I could not test it. Feedback to this, on if it works and how good is appreciated ! :smile:

**Comment by 3togo** [comment]
thank you for your prompt action. Will try your codes tonite
