### ISSUE TITLE
[bug] add_image 

### ISSUE THREAD

**Issue by 3togo** [ClementPinard/DepthNet#5]
Pls help

train.py:222: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  losses.update(loss.data[0], target.size(0))
train.py:223: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_writer.add_scalar('train_loss', loss.data[0], n_iter)
train.py:225: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  depth2_metric_errors.update(depth2_metric_error.data[0], target.size(0))
 * Avg Loss : 8.032, Avg Depth error : 16.633, normalized : 1.154
100% (2813 of 2813) |########################################| Elapsed Time: 5:35:49 ETA:  00:00:00
dfdepth2_normalized_errors.update(depth2_norm_error.data[0], target.size(0))
train.py:239: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. UsN/A% (0 of 219) |                                            | Elapsed Time: 0:00:00 ETA:  --:--:--
  writer.writerow([loss.data[0], depth2_metric_error.data[0]])
train.py:269: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  input_var = torch.autograd.Variable(torch.cat(input_tensors, 1), volatile=True)
train.py:270: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  target_var = torch.autograd.Variable(target, volatile=True)
Traceback (most recent call last):
  File "/home/jc/.local/lib/python3.6/site-packages/PIL/Image.py", line 2460, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 64), '|u1')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 301, in <module>
    main()
  File "train.py", line 158, in main
    depth_error, normalized = validate(val_loader, model, epoch, term_logger, output_writers)
  File "train.py", line 276, in validate
    output_writers[i].add_image('GroundTruth', util.tensor2array(target[0].cpu(), max_value=100), 0)
  File "/usr/local/lib/python3.6/dist-packages/tensorboardX/writer.py", line 412, in add_image

  File "/usr/local/lib/python3.6/dist-packages/tensorboardX/summary.py", line 205, in image
    image = make_image(tensor, rescale=rescale)

    image = Image.fromarray(tensor)
  File "/home/jc/.local/lib/python3.6/site-packages/PIL/Image.py", line 2463, in fromarray

TypeError: Cannot handle this data type

**Comment by ClementPinard** [comment]
This is a bug introduced with last version of TensorboardX which now expects 3xHxW tensors instead of HxWx3. Along with your multi gpu problem, I'm planning to update the code to torch 0.4.1 . Stay tuned in a few hours !

**Comment by 3togo** [comment]
many thanks下午4:03, 2018年9月3日, "Clément Pinard" <notifications@github.com>:This is a bug introduced with last version of TensorboardX which now expects 3xHxW tensors instead of HxWx3. Along with your multi gpu problem, I'm planning to update the code to torch 0.4.1 . Stay tuned in a few hours !

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

-- Sent from Yandex.Mail for mobile

**Comment by 3togo** [comment]
Only one gpu is running

<img width="424" alt="screen shot 2018-09-03 at 10 14 27 pm" src="https://user-images.githubusercontent.com/731338/44991557-fdb9d580-afc6-11e8-94ab-2043f17fd0f1.png">

**Comment by ClementPinard** [comment]
Hmmm none of your GPU is actually running for the moment, is it the same when training is active ? see some documentation on how to use multi-gpu on pytorch here : https://pytorch.org/docs/stable/nn.html#dataparallel

As said before, I don't own a multi-gpu rig so you're likely on your own for that :(
But I'll be glad to know if you succeed in making it work on multi-gpus !

**Comment by ClementPinard** [comment]
Also, as cool as it would be to this code to be runnable with multi-gpu, I don't think it's going to be useful, unless some optimization is done regarding data loading and augmentation pipeline. I think with 5 GPU the data loading will be by far your bottle neck

**Comment by 3togo** [comment]
you are right. My rough guess is that it takes more than three minutes to load the data but it might take less than one minute to run the codes.

**Comment by 3togo** [comment]
Can you tell me how to use the pretrained DepthNet?

**Comment by ClementPinard** [comment]
just use the option `--pretrained̀ within the train script to load a pretrained network, that you can download in my google drive in the README

**Comment by 3togo** [comment]
I downloaded these files but i can't untar it
Also, can u send me a sample folder for testing?
By the way, is below the correct way to test your program?
python3 train.py --pretrained Results/pretrained/DepthNet_elu_bn_128.pth.tar sample_folder




jc@:pretrained$ ls -l
total 161132
-rw-r--r-- 1 jc jc 41197810 Aug 30  2017 DepthNet_elu_bn_128.pth.tar
-rw-r--r-- 1 jc jc 41197810 Sep  1  2017 DepthNet_elu_bn_256.pth.tar
-rw-r--r-- 1 jc jc 41197806 Sep  4  2017 DepthNet_elu_bn_512.pth.tar
-rw-r--r-- 1 jc jc 41197488 Aug 30  2017 DepthNet_elu_bn_64.pth.tar

**Comment by ClementPinard** [comment]
you don't have to untar it, you just give the tar file to pretrained parameter

**Comment by 3togo** [comment]
What should I do next to use your pretrained model to estimate a depth map from a jpg and "depth maps" from a avi?
>>> data=torch.load('/home/jc/.torch/models/DepthNet_elu_bn_512.pth.tar')
>>> print("=> using pre-trained model '{}'".format(data['arch']))
=> using pre-trained model 'DepthNet_elu_bn'
>>> assert(not data['with_confidence'])

**Comment by 3togo** [comment]
Traceback (most recent call last):
  File "train.py", line 317, in <module>
    main()
  File "train.py", line 159, in main
    train_loss, train_error, train_normalized_error = train(train_loader, model, optimizer, args.epoch_size, term_logger, train_writer)
  File "train.py", line 219, in train
    for i, (input, target, _) in enumerate(train_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/data/jc/git/DepthNet/datasets/scenelistdataset.py", line 42, in __getitem__
    inputs, target = self.loader(self.root/scene['subdir'], inputs, target)
  File "/data/jc/git/DepthNet/datasets/scenelistdataset.py", line 7, in default_loader
    imgs = [imread(root/path) for path in path_imgs]
  File "/data/jc/git/DepthNet/datasets/scenelistdataset.py", line 7, in <listcomp>
    imgs = [imread(root/path) for path in path_imgs]
  File "/usr/local/lib/python3.6/dist-packages/imageio/core/functions.py", line 206, in imread
    reader = read(uri, format, 'i', **kwargs)

    request = Request(uri, 'r' + mode, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/imageio/core/request.py", line 128, in __init__

  File "/usr/local/lib/python3.6/dist-packages/imageio/core/request.py", line 271, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)

**Comment by ClementPinard** [comment]
You cannot estimate depth from a single jpg, at least not with this network.
To have depth maps from a video, you have to convert it to a list of jpg files and then you can feed it successive jpegs. Depth1 is obtained with frame0 and frame1, Depth2 from frmae1 et frame 2, and so on.

And for your error, can you tell me what options you used for this script ?

**Comment by 3togo** [comment]
can you give me an example on how to use your pretrained model plus 2 jpegs to estimate depth?
