### ISSUE TITLE
ELU+1 Activation.

### ISSUE THREAD

**Issue by jrodriguezpuigvert** [ClementPinard/DepthNet#7]
Hi, thank you very much for sharing your work.  I was wondering if you can explain a bit why are you using ELU+1. And if you have some thoughts about why is performing better.

**Comment by ClementPinard** [comment]
Hello, thanks for your interest in this work.

You can dinf a detailed explanation in my thesis https://clementpinard.fr/pdf/PhdThesis/robust_depth_learning_thesis.pdf, page 38

TLDR, unlike ReLU, the gradient of ELU is never 0 which is better for convergence, espcially as the last layer. The +1 comes for the fact that depth is never negative and ELU +1 exactly reflects that :)

**Comment by jrodriguezpuigvert** [comment]
Thank you very much for the link! I was wondering if you have some experiments using Sigmoid and then a linearity between max depth and min depth.
Do you think that can make that sense?

**Comment by ClementPinard** [comment]
I does make sense. After all, the left part of ELU is very similar to the sigmoid, so this activation function would only be signficantly different outside of max depth.

Machin learning being machine learning, it can yield better results, but I doubt the result will be very different from using 1+ELU
